# Server 3
storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d

# a list of other known repositories we can talk to
uplinks:
  server2:
    url: http://verdaccio2:4873/
#    auth:
#      type: bearer
#      token: "NkbcJYnuB8Z6XO4kImS2pw=="

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: server2
  '**':
    access: $all
    publish: $authenticated
    proxy: server2

middlewares:
  audit:
    enabled: true

logs:
  - {type: stdout, format: pretty, level: trace}
