version: '3'
services:
  verdaccio:
    image: verdaccio/verdaccio:4.x-next
    container_name: verdaccio-multi-1
    ports:
      - "4873:4873"
    volumes:
        - "./server1/storage:/verdaccio/storage"
        - "./server1/conf:/verdaccio/conf"
    links:
      - verdaccio3:verdaccio3
    depends_on:
      - verdaccio3
  verdaccio2:
    image: verdaccio/verdaccio:2
    container_name: verdaccio-multi-2
    ports:
      - "4874:4873"
    volumes:
        - "./server2/storage:/verdaccio/storage"
        - "./server2/conf:/verdaccio/conf"
  verdaccio3:
    image: verdaccio/verdaccio:3
    container_name: verdaccio-multi-3
    ports:
      - "4875:4873"
    links:
      - verdaccio2:verdaccio2
    volumes:
        - "./server3/storage:/verdaccio/storage"
        - "./server3/conf:/verdaccio/conf"
    depends_on:
      - verdaccio2
volumes:
  verdaccio:
    driver: local
  verdaccio2:
    driver: local
  verdaccio3:
    driver: local
